app_type = "simple"
python_version = "3.12"
registered_name = "webinar-autodesk-revit-structural-agent"
oauth2_integrations = [
    "aps-automation-webinar-alejandro"
]
worker_integrations = [
    "sap2000",
]
